apiVersion: v1
data:
  DATABASE_SESSION_POOLER: ""
  ENCRYPTION_KEY: ""
  ENGINE_API_SECRET: ""
  GOCARDLESS_SECRET_ID: ""
  GOCARDLESS_SECRET_KEY: ""
  JWT_SECRET: ""
  LOOPS_API_KEY: ""
  MISTRAL_API_KEY: ""
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ""
  NEXT_PUBLIC_SUPABASE_URL: ""
  OPENAI_API_KEY: ""
  PLAID_CLIENT_ID: ""
  PLAID_SECRET: ""
  RESEND_API_KEY: ""
  SUPABASE_SERVICE_ROLE_KEY: ""
  TRIGGER_API_KEY: ""
  TRIGGER_API_URL: ""
kind: Secret
metadata:
  name: workbooks-api-secrets
  namespace: default
