---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-config
  namespace: cloudflare
data:
  config.yaml: |
    tunnel: workbooks-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: workbooks.tocld.com
        service: http://workbooks-dashboard.default:3001
      - hostname: workbooks-api.tocld.com
        service: http://workbooks-api.default:3003
      - service: http_status:404